// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzpycxpmpmvlogixflhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16cHljeHBtcG12bG9naXhmbGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzMzMjYsImV4cCI6MjA2NDcwOTMyNn0.WOzkgpTS4duSJCI_U5trpvLth0miaI-Adi-IUDft59M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);